--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xenophilicy/CrashTransfer
build-by-default: true
branches:
- PM4
projects:
  CrashTransfer:
    path: ""
    lint:
      phpstan: false
...
