--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xenophilicy/CrashTransfer 
build-by-default: true
branches:
- master
projects:
  CrashTransfer:
    path: ""
    lint:
      phpstan: false
...
